# Generated by Django 5.1.4 on 2024-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
