# Generated by Django 5.1.4 on 2024-12-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_joined_date_portfolio_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
