# Generated by Django 5.1.4 on 2024-12-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='created_by',
        ),
    ]
