# Generated by Django 5.1.4 on 2024-12-21 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='password',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='username',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
